apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "aws-auth-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "aws-auth-operator.labels" . | nindent 8 }}
        control-plane: controller-manager
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - args:
          - --config-map-name={{ .Values.configMapName }}
          - --must-present-account-id={{ .Values.mustPresentAccountID }}
          - --crd-item-allowed-namespace={{ .Values.crdCreationAllowedNS }}
          - --reconcile-time={{ .Values.reconcileTime }}
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
        {{- with .Values.controllerArguments -}}
          {{ toYaml . | nindent 10 }}
        {{- end }}
        command:
        - /manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
         {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: webhook-certs
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "aws-auth-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "aws-auth-operator.fullname" . }}-webhook-server-cert
