apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
  name: aws-auth-operator-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: aws-auth-operator-selfsigned-issuer
  secretName: webhook-server-cert