{{- if .Values.selfSignedIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
  name: {{ include "aws-auth-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "aws-auth-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "aws-auth-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "aws-auth-operator.fullname" . }}-selfsigned-issuer
  secretName: {{ include "aws-auth-operator.fullname" . }}-webhook-server-cert
{{- end }}