apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- if .Values.selfSignedIssuer.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "aws-auth-operator.fullname" . }}-serving-cert
    {{- end }}
  name: {{ include "aws-auth-operator.fullname" . }}-validating-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "aws-auth-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-aws-auth-prozorro-sale-v1beta1-mapaccount
    failurePolicy: Fail
    name: vmapaccount-v1beta1.kb.io
    rules:
      - apiGroups:
          - aws-auth.prozorro.sale
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - mapaccounts
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "aws-auth-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-aws-auth-prozorro-sale-v1beta1-maprole
    failurePolicy: Fail
    name: vmaprole-v1beta1.kb.io
    rules:
      - apiGroups:
          - aws-auth.prozorro.sale
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - maproles
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "aws-auth-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-aws-auth-prozorro-sale-v1beta1-mapuser
    failurePolicy: Fail
    name: vmapuser-v1beta1.kb.io
    rules:
      - apiGroups:
          - aws-auth.prozorro.sale
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - mapusers
    sideEffects: None