apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapUser
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: test2
spec:
  description: A test mapuser
  username: test1.user@ios.in.ua
  groups:
    - test:group
  userarn: arn:aws:iam::123456789012:user/sample-mapuser1-1
