apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapUser
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: user1
spec:
  description: A test mapuser
  username: user1@ios.in.ua
  groups:
    - system:masters
    - admins
  userarn: arn:aws:iam::123456789012:user/user1

---
apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapUser
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: user2
spec:
  description: A test mapuser
  username: user2@ios.in.ua
  groups:
    - system:masters
    - users
  userarn: arn:aws:iam::123456789012:user/user2

---
apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapUser
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: serhii.rudenko
spec:
  description: Serhii Rudenko
  username: sr@ios.in.ua
  groups:
    - system:masters
    - users
    - admins
  userarn: arn:aws:iam::123456789012:user/sr@ios.in.ua