apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapRole
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: maprole_prod-self-managed-node-group
spec:
  rolearn: arn:aws:iam::130488995195:role/prod-self-managed-node-group
  groups:
    - sample:group1
    - sample:group2
  description: A sample maprole
  username: system:node:{{EC2PrivateDNSName}}

---

apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapRole
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: maprole_self-mng-single-az-node-group
spec:
  rolearn: arn:aws:iam::130488995195:role/self-mng-single-az-node-group-20240218223715755100000001
  groups:
    - sample:group1
    - sample:group2
    - sample:group3
  description: A sample maprole
  username: system:node:{{EC2PrivateDNSName2}}