apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: account1
spec:
  accountid: "111111111111"

---

apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: account2
spec:
  accountid: "130488995195"
