apiVersion: aws-auth.prozorro.sale/v1beta1
kind: MapAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-auth-controller-prozorro
    app.kubernetes.io/managed-by: kustomize
  name: mapaccount-sample1
spec:
  accountid: "111111111113"

#---
#
#apiVersion: aws-auth.prozorro.sale/v1beta1
#kind: MapAccount
#metadata:
#  labels:
#    app.kubernetes.io/name: aws-auth-controller-prozorro
#    app.kubernetes.io/managed-by: kustomize
#  name: mapaccount-sample2
#spec:
#  accountid: "222222222222"