# Default values for aws-auth-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Controller Pod replica count
replicaCount: 2

image:
  # -- Image repository
  repository: ghcr.io/redacid/aws-auth-controller
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag, will override the default tag derived from the chart app version
  tag: "0.1.0"

# -- Image pull secrets
imagePullSecrets: []
# -- Override the `name` of the chart
nameOverride: ""
# -- Override the `fullname` of the chart
fullnameOverride: ""

# -- Annotations to add to the pod
podAnnotations: {}
# -- Security context for the manager container
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podSecurityContext:
  #{}
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault


resources:
  #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Controller-specific config

podDisruptionBudget:
  enabled: false

selfSignedIssuer:
  enabled: true

configMapName: "aws-auth-test"
mustPresentAccountID: "123456789012"
crdCreationAllowedNS: "kube-system"
reconcileTime: "30m"

controllerArguments:
  #{}
  - --zap-devel=true
  - --zap-encoder=console
  - --zap-log-level=info
  - --zap-time-encoding=iso8601
  - --zap-stacktrace-level=panic
